INSERT OR IGNORE INTO sources
    (id, publisher, canonical_url, source_tier, fetch_method, trust_notes,
     polling_interval_minutes, source_role, adapter_config_json)
VALUES
    ('source_uber_engineering', 'Uber Engineering', 'https://www.uber.com/us/en/blog/engineering/', 2, 'html',
     'Official Uber engineering publication', 360, 'technical_editorial',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/us/en/blog/"]}'),
    ('source_spotify_engineering', 'Spotify Engineering', 'https://engineering.atspotify.com/feed/', 2, 'rss',
     'Official Spotify engineering publication', 360, 'technical_editorial', '{"adapter":"feed"}'),
    ('source_discord_blog', 'Discord Blog', 'https://discord.com/blog/rss.xml', 2, 'rss',
     'Official Discord publication with engineering and platform posts', 360, 'technical_editorial',
     '{"adapter":"feed"}'),
    ('source_nvidia_technical_blog', 'NVIDIA Technical Blog', 'https://developer.nvidia.com/blog/feed/', 1, 'atom',
     'Official NVIDIA developer and technical publication', 240, 'primary', '{"adapter":"feed"}'),
    ('source_mistral_news', 'Mistral News', 'https://mistral.ai/news/', 1, 'html',
     'Official Mistral model, research, engineering, and product publication', 240, 'primary',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/news/"]}'),
    ('source_google_project_zero', 'Google Project Zero', 'https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss', 1, 'rss',
     'Official Google Project Zero vulnerability research', 240, 'primary', '{"adapter":"feed"}'),
    ('source_google_security_blog', 'Google Security Blog', 'https://feeds.feedburner.com/GoogleOnlineSecurityBlog', 1, 'rss',
     'Official Google security research and platform-security publication', 240, 'primary', '{"adapter":"feed"}'),
    ('source_chrome_developers', 'Chrome for Developers', 'https://developer.chrome.com/static/blog/feed.xml', 1, 'rss',
     'Official Chrome web-platform and developer publication', 240, 'primary', '{"adapter":"feed"}'),
    ('source_docker_blog', 'Docker Blog', 'https://www.docker.com/blog/feed/', 1, 'rss',
     'Official Docker product and engineering publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_gitlab_releases', 'GitLab Releases', 'https://about.gitlab.com/releases.xml', 1, 'rss',
     'Official GitLab release feed', 240, 'primary', '{"adapter":"feed"}'),
    ('source_stripe_engineering', 'Stripe Engineering', 'https://stripe.com/blog/feed.rss', 2, 'rss',
     'Official Stripe publication, ranked for engineering and infrastructure posts', 360, 'technical_editorial',
     '{"adapter":"feed"}'),
    ('source_cloudflare_research', 'Cloudflare Research', 'https://research.cloudflare.com/focus/', 1, 'html',
     'Official Cloudflare research index and its Cloudflare engineering publications', 360, 'primary',
     '{"adapter":"html_listing","item_limit":12,"allowed_hosts":["blog.cloudflare.com"],"path_prefixes":["/","/research/"]}'),
    ('source_arxiv_distributed', 'arXiv · Distributed Computing', 'https://export.arxiv.org/rss/cs.DC', 2, 'rss',
     'arXiv distributed-computing research discovery', 360, 'technical_editorial', '{"adapter":"feed"}'),
    ('source_usenix_publications', 'USENIX Publications', 'https://www.usenix.org/publications/proceedings', 2, 'html',
     'Official USENIX systems and security proceedings index', 720, 'technical_editorial',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/conference/"]}'),
    ('source_acm_cacm', 'Communications of the ACM', 'https://cacm.acm.org/feed/', 2, 'rss',
     'Official ACM computing research and practitioner publication', 720, 'technical_editorial',
     '{"adapter":"feed"}'),
    ('source_trail_of_bits', 'Trail of Bits Blog', 'https://blog.trailofbits.com/feed/', 1, 'rss',
     'Original security research from Trail of Bits', 240, 'primary', '{"adapter":"feed"}'),
    ('source_ncc_research', 'NCC Group Research', 'https://www.nccgroup.com/research/', 1, 'html',
     'Original security research from NCC Group', 360, 'primary',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/research/"]}'),
    ('source_msrc_blog', 'Microsoft Security Response Center', 'https://www.microsoft.com/en-us/msrc/blog', 1, 'html',
     'Official Microsoft security response and vulnerability research publication', 240, 'primary',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/en-us/msrc/blog/"]}'),
    ('source_duckdb_blog', 'DuckDB Blog', 'https://duckdb.org/feed.xml', 1, 'rss',
     'Official DuckDB engineering and release publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_clickhouse_blog', 'ClickHouse Blog', 'https://clickhouse.com/rss.xml', 1, 'rss',
     'Official ClickHouse engineering and product publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_cockroach_blog', 'Cockroach Labs Blog', 'https://www.cockroachlabs.com/blog/', 2, 'html',
     'Official CockroachDB publication, ranked for database engineering content', 360, 'technical_editorial',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/blog/"]}'),
    ('source_sqlite_releases', 'SQLite Releases', 'https://sqlite.org/src/timeline.rss?y=ci&t=release', 1, 'rss',
     'Official SQLite Fossil release timeline', 720, 'primary', '{"adapter":"feed"}'),
    ('source_typescript_blog', 'TypeScript Blog', 'https://devblogs.microsoft.com/typescript/feed/', 1, 'rss',
     'Official TypeScript release and engineering publication', 240, 'primary', '{"adapter":"feed"}'),
    ('source_dotnet_blog', '.NET Blog', 'https://devblogs.microsoft.com/dotnet/feed/', 1, 'rss',
     'Official .NET release and engineering publication', 240, 'primary', '{"adapter":"feed"}'),
    ('source_inside_java', 'Inside Java', 'https://inside.java/feed.xml', 1, 'rss',
     'Official OpenJDK and Java platform publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_kotlin_blog', 'Kotlin Blog', 'https://blog.jetbrains.com/kotlin/feed/', 1, 'rss',
     'Official Kotlin language and tooling publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_deno_blog', 'Deno Blog', 'https://deno.com/blog', 1, 'html',
     'Official Deno runtime and platform publication', 360, 'primary',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/blog/"]}'),
    ('source_bun_blog', 'Bun Blog', 'https://bun.sh/rss.xml', 1, 'rss',
     'Official Bun runtime publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_hashicorp_blog', 'HashiCorp Blog', 'https://www.hashicorp.com/blog/feed.xml', 1, 'rss',
     'Official HashiCorp infrastructure publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_grafana_blog', 'Grafana Labs Blog', 'https://grafana.com/blog/index.xml', 1, 'rss',
     'Official Grafana Labs observability publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_datadog_blog', 'Datadog Blog', 'https://www.datadoghq.com/blog/index.xml', 2, 'rss',
     'Official Datadog publication, ranked for engineering and operations content', 360, 'technical_editorial',
     '{"adapter":"feed"}'),
    ('source_fly_blog', 'Fly.io Blog', 'https://fly.io/blog/feed.xml', 2, 'rss',
     'Official Fly.io engineering publication', 360, 'technical_editorial', '{"adapter":"feed"}'),
    ('source_tailscale_blog', 'Tailscale Blog', 'https://tailscale.com/blog/index.xml', 2, 'rss',
     'Official Tailscale networking and security publication', 360, 'technical_editorial',
     '{"adapter":"feed"}'),
    ('source_meta_ai', 'Meta AI', 'https://ai.meta.com/blog/', 1, 'html',
     'Official Meta AI research and engineering publication', 360, 'primary',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/blog/"]}'),
    ('source_google_developers_blog', 'Google Developers Blog', 'https://developers.googleblog.com/feeds/posts/default?alt=rss', 1, 'rss',
     'Official Google developer and AI platform publication', 240, 'primary', '{"adapter":"feed"}'),
    ('source_huggingface_transformers', 'Hugging Face Transformers Releases', 'https://api.github.com/repos/huggingface/transformers/releases', 1, 'api',
     'Official Transformers repository releases', 360, 'primary',
     '{"adapter":"github_releases","item_limit":20}'),
    ('source_huggingface_hub', 'Hugging Face Hub Client Releases', 'https://api.github.com/repos/huggingface/huggingface_hub/releases', 1, 'api',
     'Official Hugging Face Hub client repository releases', 360, 'primary',
     '{"adapter":"github_releases","item_limit":20}'),
    ('source_huggingface_tgi', 'Hugging Face TGI Releases', 'https://api.github.com/repos/huggingface/text-generation-inference/releases', 1, 'api',
     'Official Text Generation Inference repository releases', 360, 'primary',
     '{"adapter":"github_releases","item_limit":20}'),
    ('source_airbnb_engineering', 'Airbnb Engineering', 'https://medium.com/feed/airbnb-engineering', 2, 'rss',
     'Official Airbnb Engineering publication hosted on Medium', 360, 'technical_editorial',
     '{"adapter":"feed"}'),
    ('source_doordash_engineering', 'DoorDash Engineering', 'https://careersatdoordash.com/blog/feed/', 2, 'rss',
     'Official DoorDash engineering publication', 360, 'technical_editorial', '{"adapter":"feed"}'),
    ('source_shopify_engineering', 'Shopify Engineering', 'https://shopify.engineering/blog.atom', 2, 'atom',
     'Official Shopify engineering publication', 360, 'technical_editorial', '{"adapter":"feed"}'),
    ('source_figma_engineering', 'Figma Engineering', 'https://www.figma.com/blog/engineering/', 2, 'html',
     'Official Figma engineering publication', 360, 'technical_editorial',
     '{"adapter":"html_listing","item_limit":12,"path_prefixes":["/blog/"]}'),
    ('source_ietf_blog', 'IETF Blog', 'https://www.ietf.org/blog/feed/', 1, 'rss',
     'Official IETF protocol and standards publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_whatwg_blog', 'WHATWG Blog', 'https://blog.whatwg.org/feed', 1, 'rss',
     'Official WHATWG web-platform standards publication', 360, 'primary', '{"adapter":"feed"}'),
    ('source_w3c_news', 'W3C News', 'https://www.w3.org/news/feed/', 1, 'rss',
     'Official W3C web-standards publication', 360, 'primary', '{"adapter":"feed"}');

INSERT INTO schema_migrations(version, name)
VALUES (12, 'expand_radar_sources');
