package store

var RequiredInitialTables = []string{
	"users",
	"sessions",
	"invites",
	"learning_profiles",
	"learning_preferences",
	"delivery_schedules",
	"delivery_destinations",
	"topics",
	"user_topic_preferences",
	"learning_paths",
	"theme_blocks",
	"sources",
	"source_items",
	"radar_candidates",
	"lessons",
	"lesson_source_items",
	"lesson_parts",
	"lesson_assignments",
	"deliveries",
	"delivery_parts",
	"interactions",
	"reviews",
	"decisions",
	"provider_runs",
	"prompt_versions",
	"cache_entries",
	"job_queue",
}
